#!/bin/sh
#
# Copyright 2020 eBlocker Open Source UG (haftungsbeschraenkt)
#
# Licensed under the EUPL, Version 1.2 or - as soon they will be
# approved by the European Commission - subsequent versions of the EUPL
# (the "License"); You may not use this work except in compliance with
# the License. You may obtain a copy of the License at:
#
#   https://joinup.ec.europa.eu/page/eupl-text-11-12
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.
#

# process pid is managed by the eblocker-dns itself but systemd needs a pidfile
# to handle the service correctly. A red-hat only option "pidfile" exists which
# is picked up systemd's sysv-generator but it has to be placed before the lsb
# header (see also EB1-709).
#
# pidfile: /opt/eblocker-dns/run/eblocker-dns.pid
#
### BEGIN INIT INFO
# Provides:          eblocker-dns
# Required-Start:    $local_fs $network redis-server
# Required-Stop:     $local_fs $network redis-server
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: eblocker-dns initscript
# Description:       eblocker-dns
### END INIT INFO

EBLOCKER_DNS_HOME=/opt/eblocker-dns

eblocker_dns ()
{
    cd $EBLOCKER_DNS_HOME

    # See also: /etc/security/limits.d/eblocker-dns.conf
    ulimit -n 10000

    su eblocker-dns -s /bin/sh -c "bin/eblocker-dns $1"
}

case "$1" in
    start)
	eblocker_dns start
	;;
    stop)
	eblocker_dns stop
	;;
    restart)
	eblocker_dns restart
	;;
    status)
	eblocker_dns status
	;;
    *)
	echo "Usage: $SCRIPT_NAME {start|stop|restart|status}" >&2
	exit 3
	;;
esac
